- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
      - node
      - zsh
      - install
  tasks:
    - include: default-tasks/ssh.yml
    - include: default-tasks/git.yml
    - include: default-tasks/core.yml
    - include: default-tasks/zsh.yml
    - include: default-tasks/rust.yml
    - include: default-tasks/node.yml
    - include: default-tasks/npm-packages.yml
    - include: default-tasks/productivity.yml
    - include: default-tasks/nvim.yml
    - include: default-tasks/dotfiles.yml
