- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
      - node
      - zsh
      - install
  tasks:
  - include: default-tasks/zsh.yml
  - include: default-tasks/node.yml
  - include: default-tasks/productivity.yml
  - include: default-tasks/dotfiles.yml
