---
downloads: ~/.ansible-downloads/

configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Mail
  - Maps
  - FaceTime
  - Calendar
  - Contacts - Reminders - Notes - Music
  - News
  - Keynote
  - Numbers
  - Messages
  - Safari
dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 1
  - name: "1Password"
    path: "/Applications/1Password.app/"
    pos: 2
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
    pos: 3
  - name: "iTerm2"
    path: "/Applications/iTerm.app/"
    pos: 4
  - name: "Telegram"
    path: "/Applications/Telegram.app"
    pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  - asdf
  - ninja
  - libtool
  - cmake
  - pkg-config
  - gettext
  - tmux
  - gnupg
  - stow

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - 1password
  - spotify
  - telegram
  - handbrake
  - slack
  - postman
  - iterm2
  - postgres-unofficial

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

