---
- name: Install dockutil.
  homebrew:
    name: dockutil
    state: present
  notify:
    - Clear homebrew cache

- name: Remove configured Dock items.
  ansible.builtin.include_tasks: mac-tasks/dock-remove.yml
  loop: "{{ dockitems_remove }}"

- name: Ensure required dock items exist.
  ansible.builtin.include_tasks: mac-tasks/dock-add.yml
  loop: "{{ dockitems_persist }}"

