- name: Add asdf to path
  shell: sh -c 'echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ~/.zshrc'
  tags:
    - zsh
 
- name: Add asdf autocomplete to path
  shell: sh -c 'echo -e "\n. $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash"  >> ~/.zshrc'
  tags:
    - zsh

- name: Remove ohmyzsh 
  shell: rm -rf ~/.oh-my-zsh
  tags:
    - zsh 

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
  - zsh

- name: Install zsh plugin autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
  - zsh
