- name: install frum / ruby package manager
  community.general.cargo:
    name: frum
  tags:
    - rust

- name: initialise
  lineinfile:
    path: "~/.zshrc"
    line: eval "$(frum init)"
  tags:
    - ruby

- name: download openssl 1.1.1 for ruby 2.7.6
  ansible.builtin.get_url:
    url: 'https://www.openssl.org/source/openssl-1.1.1q.tar.gz'
    dest: '/tmp'
  tags:
    - ruby
    - ruby-2

- name: extract openssl 1.1.1
  ansible.builtin.unarchive:
    src: '/tmp/openssl-1.1.1q.tar.gz'
    dest: '/tmp/'
  tags:
    - ruby-2

- name: configure openssl
  shell:
    cmd: './config --prefix=/opt/openssl-1.1.1q --openssldir=/opt/openssl-1.1.1q shared zlib'
    chdir: '/tmp/openssl-1.1.1q'
  tags:
    - ruby-2

- name: openssl make test
  make:
    target: test
    chdir: '/tmp/openssl-1.1.1q'
  tags:
    - ruby-2

- name: openssl make install
  become: true
  shell: 
    cmd: 'make install'
    chdir: '/tmp/openssl-1.1.1q'
  tags:
    - ruby-2

- name: prepare certs
  become: true
  ansible.builtin.file:
    path: '/opt/openssl-1.1.1q/certs'
    state: absent
  tags:
    - ruby-2

- name: symlink openssl
  become: true
  ansible.builtin.file:
    dest: '/opt/openssl-1.1.1q/certs'
    src: '/etc/ssl/certs'
    state: link
  tags:
    - ruby-2

- name: install 2.7.6
  shell: sh -c "$(frum install 2.7.6 --with-openssl-dir=/opt/openssl-1.1.1q)"
  tags:
    - ruby-install

